config/routes.rb
Rails.application.routes.draw do
  
 
  root :to => 'pages#home'
  resources :items
  resources :users, :only => [:new, :create, :index]
  resources :categories

  get '/checkout/:id' => 'pages#checkout', :as => "checkout"
  post '/finished/:id' => 'pages#finished' 

  # resources :mixtapes, :only => [:new, :create]

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/User.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, :uniqueness => true, :presence => true
    has_many :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :user, :optional => true 
    belongs_to :categories, :optional => true 
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, :uniqueness => true, :presence => true
    has_many :items
end

app/models/xuser.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, :uniqueness => true, :presence => true
    has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :fetch_user

    def fetch_user
        @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
        session[:user_id] = nil unless @current_user.present? # Log out non-existent users.
    end

    def check_for_login
        redirect_to login_path unless @current_user.present?
    end

    def check_for_admin
        redirect_to login_path unless (@current_user.present? && @current_user.admin?)
    end
end
    

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find params[:id]
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all 
  end

  def show
    @item = Item.find params[:id]
  end

  def edit
    @item=  Item.find params[:id] 
  end

  def new
    @item = Item.new 
    @categories = Category.all
  end

  def destroy
    item = Item.find params[:id]
    item.destroy
    if (@current_user == item.user)
      redirect_to items_path 
    else
      render "finished"
    end  
  end

  def update
    item = Item.find params[:id]
    item.update item_params
    redirect_to item
  end

  def create
    item = Item.create item_params
    @current_user.items << item # Give the new mixtape to the current user
    redirect_to items_path # IRL redirect to mixtape or somewhere
  end

  

  private
  # Strong params
  def item_params
    params.require(:item).permit(:name, :price, :description, :image, :category_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    
    def checkout
      @item=Item.find params[:id]
    end

    def finished
      item = Item.find params[:id]
      item.destroy
    end
  end

app/controllers/session_controller.rb
class SessionController < ApplicationController
    def new
    end
  
    def create
      user = User.find_by :email => params[:email]
      if user.present? && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to root_path
      else
        flash[:error] = "Sorry, login failed"
        redirect_to login_path
      end
    end
  
    def destroy
      session[:user_id] = nil
      redirect_to login_path
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :check_for_admin, :only => [:index]
  
    def index
      @users = User.all
    end
  
    def new
      @user = User.new
    end
  
    def create
      @user = User.new user_params
      if @user.save
        session[:user_id] = @user.id
        redirect_to root_path
      else
        render :new
      end
    end
  
    private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/categories/index.html.erb
<h1>All Categories </h1>

<% @categories.each do |category| %>

    <ul>
        <li>Name: <%= link_to category.name, category %></li>
    </ul>

    

<% end %>

app/views/categories/show.html.erb
<h1>Categories</h1>
<%= @category.name %>
<% @category.items.each do |item|%>
     <div class="box">
        <%= image_tag item.image, :class => "thumb" %>

            <ul>
                <li>Name: <%= link_to item.name, item %></li>
                <li>Price: <%= item.price %></li>
            
                <li>Description: <%= item.description  %></li>
            
                <li>Image: <%= item.image %></li>
            </ul>
        </div>
        
<%end%>

app/views/items/_form.html.erb
<div class="form-group">
    <%= form_for @item do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name, :required => true %>
<div>
<div class="form-group">
        <%= f.label :description %>
        <%= f.text_field :description %>
</div>
<div class="form-group">
        <%= f.label :price%>
        <%= f.text_field :price%>
<div>
<div class="form-group">
        <%= f.label :image, "paste URl with items photo" %>
        <%= f.url_field :image %>
<div>
<div class="form-group">
        <%= f.label :category_id, "Select a category:"%>
        <%= f.select :category_id, Category.pluck(:name, :id) %>
<div>
    
    <%= f.submit %>
<% end %>

app/views/items/edit.html.erb
<h1> Edit Item Listing </h1>
<%= render :partial => 'form' %>

app/views/items/finished.html.erb
<h1> finished </h1>

app/views/items/index.html.erb
<h1>All Items</h1>
<div class="container">
    <div class="controls">
        <%= link_to 'Create New Listing', new_item_path(@item) %>
        </div>

    <% @items.each do |item| %>
        <div class="box">
        <%= image_tag item.image, :class => "thumb" %>

            <ul>
                <li>Name: <%= link_to item.name, item %></li>
                <li>Price: <%= item.price %></li>
            
                <li>Description: <%= item.description  %></li>
            
                <li>Image: <%= item.image %></li>
            </ul>
        </div>
        

    <% end %>
    
</div> 

app/views/items/new.html.erb
<div class="listing">
<h1>Create a New Listing</h1>
</div>



<%= render :partial => 'form' %>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>

<%= image_tag @item.image, :class => 'feature' if @item.image.present? %>
<ul>
    <li>Name: <%= @item.name %></li>
    <li>Description: <%= @item.description %></li>
    
</ul>
<% if @current_user.present?%>
    <%=link_to 'Buy This Item', checkout_path(params[:id])  %>
 <% if @item.user == @current_user %>
<div class="controls">
    <%= link_to 'Edit Item Listing', edit_item_path(@item) %>
    <%= link_to 'Delete Item Listing', @item, :method => 'delete', :data => { :confirm => 'Are you sure?' } %>
    
</div>
<%end%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sell Ya Junk.</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav>
      <%= link_to 'Home', root_path %>
      <% if @current_user.present? %>
        <%= link_to "All users", users_path if @current_user.admin? %>
       
        <%= link_to "Logout #{ @current_user.email }", login_path, :method => 'delete' %>
      <% else %>
        <%= link_to 'Sign up', new_user_path %>
        <%= link_to 'Sign in', login_path %>
      <% end %>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_for @pages do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, :required => true %>

    <%= f.label :description %>
    <%= f.text_field :description %>

    <%= f.label :price%>
    <%= f.text_field :price%>

    <%= f.label :image, "paste URl with items photo" %>
    <%= f.url_field :image %>

    <%= f.select :category_id, Category.pluck(:name, :id) %>

    
    <%= f.submit %>
<% end %>

app/views/pages/checkout.html.erb
<h1> Checkout</h1>
<body>
<p>You selected the following item: </p>

<p> Please insert your payment detailes bellow </p>

<form action=<%="/finished/#{params[:id]}"%> method='post'>

  <label for="cname"> Name on Card :</label><br>
  <input type="text" id="fname" name="fname" value=""><br>
  <label for="cnumber">Card Number:</label><br>
  <input type="integer" id="cnumber" name="cnumber" value=""><br><br>
  <label for="pin"> 3 Digits at the back of the Card:
  <input type="integer" id="pin" name="pin" value=""><br><br>
</form> 

  <%= button_to "checkout" ,@item, :method => :delete, :class => "btn btn-success"%>



<p>If you click the "Submit" button,you will be charged".</p>
<body>

app/views/pages/home.html.erb
<div class="title">

    <h1><mark>Jacaranda Tree<mark></h1>



<h2> <mark>Buy and Sell used items.<mark> </h2>
</div>
<p>Welcome back user <%= @current_user.email if @current_user.present? %></p>


<div class="controls">
    <%= link_to 'See all items listings' , items_path %>
    <%= link_to 'Browse by category', categories_path %>
</div>

app/views/session/new.html.erb
<h1>Log In</h1>

<% if flash[:error].present? %>
    <h2><%= flash[:error] %></h2>
<% end %>
<%= form_tag login_path do %>
    <%= label_tag :email %>
    <%= email_field_tag :email %>

     <div class="form-group">
        <%= label_tag :password %>
        <%= password_field_tag :password, nil, :class => 'form-control' %>
    </div>

    <%= submit_tag "Sign in", :class => 'btn btn-success btn-lg' %>
<% end %>

app/views/users/index.html.erb
<h1>All users</h1>

<h2><%= @users.count %> users</h2>

<% @users.each do |user| %>
    <p><%= user.email %></p>
<% end %> 

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
    <ol>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ol>
<% end %>
<%= form_for @user do |f| %>
    <%= f.label :email %>
    <%= f.email_field :email %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    <%= f.submit "Sign up!" %>
<% end %>